name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install --system -r requirements.txt
          uv pip install --system -r requirements-dev.txt
          uv pip install --system -r infra/requirements.txt
          uv pip install --system .
          uv pip install --system ruff
          uv pip install --system bandit
      - name: Ruff
        run: ruff check .
      - name: Bandit
        run: bandit -c .bandit.yml -r src/qs_kdf
      - name: Tests
        run: |
          uv pip install --system pytest pytest-cov
          pytest --cov=src --cov-report=xml --cov-fail-under=70
      - name: Upload coverage
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: CDK Synth
        working-directory: infra
        run: cdk synth
        continue-on-error: true
