name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install argon2-cffi
          pip install ruff
          pip install -r infra/requirements.txt
      - name: Ruff
        run: ruff check .
      - name: Tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=src --cov-report=xml --cov-fail-under=70
      - name: CDK Synth
        working-directory: infra
        run: cdk synth
        continue-on-error: false
