name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ruff
        run: ruff check .
      - name: Tests
        run: |
          pip install pytest coverage
          coverage run -m pytest
          coverage xml
      - name: Coverage Badge
        run: |
          pip install coverage-badge
          coverage-badge -o coverage.svg -f
      - name: Fail if coverage <70%
        run: |
          rate=$(python - <<'PY'
import xml.etree.ElementTree as ET
rate=float(ET.parse('coverage.xml').getroot().get('line-rate'))*100
print(int(rate))
PY
          )
          echo "Coverage ${rate}%"
          if [ "$rate" -lt 70 ]; then
            echo "Coverage below threshold"
            exit 1
          fi
      - name: Terraform Validate
        run: terraform validate terraform
        continue-on-error: true
